---
# tasks file for logging
- name: Criar o arquivo de log de acessos
  become: true
  ansible.builtin.file:
    path: /dados/nfs/acessos
    state: touch
    mode: "0666"

- name: Criar o script de monitoramento de login
  become: true
  ansible.builtin.copy:
    dest: /usr/local/bin/log_login.sh
    content: |
      #!/bin/bash
      # Script para monitorar logins
      LOG_FILE="/dados/nfs/acessos"
      TIMESTAMP=$(date '+%Y-%m-%d %H:%M')
      USER=$USER
      TTY=$SSH_TTY
      IP=$(who -m | awk '{print $NF}' | tr -d '()')

      # Escreve no arquivo de log
      echo "${TIMESTAMP}; ${USER}; ${TTY}; ${IP}" >> "$LOG_FILE"
    mode: "0755"

- name: Configurar para executar o script no login
  become: true
  ansible.builtin.lineinfile:
    path: /etc/profile
    line: "/usr/local/bin/log_login.sh"
    state: present
